= Master thesis project

The base application for the canary rollouts will be either the DUViewer incl. die PACSGate and DICOMServices as backend or the application from Service Egnineering lecture: A micro-service based car rental web shop. 

The coding languages can be reduced to: 
- Angular
- Java using Spring Framework

== Toolstacks

* https://spinnaker.io/docs/guides/user/canary/[Spinnaker Canary] 
  -> currently not working setup

* https://fluxcd.io/flux/[FluxCD Flagger] with Different Ingress Controller or Service Meshes
  -> deployment done - works like a charm i like

* https://kubernetes.io/blog/2020/04/two-phased-canary-rollout-with-gloo/[Kubernetes phased rollout using Gloo] with https://istio.io/latest/blog/2017/0.1-canary/[Istio Canary Deployment]

* https://argoproj.github.io/argo-rollouts/features/canary/[Argo Rollouts] with https://istio.io/latest/blog/2017/0.1-canary/[Istio Canary Deployment]

* https://keptn.sh/docs/0.16.x/continuous_delivery/deployment_helm/[Keptn] 

For generating load https://github.com/rakyll/hey[HEY]

== Local infrastructure

For local setup Vagrant is used. Vagrant comes with a concept of boxes, which essentially are images of ready made virtual machines. Various images can be downloaded from https://app.vagrantup.com/boxes/search[Vagrant Cloud]. The defintion of infrastructure is done in a file called "Vagrantfile". Following commands can be used to initiate the creation of local infrastructure. 

Prerequisites: 
* Virtual Box
* Vagrant, incl. vagrant-disksize plugin

[,bash]
---
brew install vagrant
brew install ngrok/ngrok/ngrok
vagrant plugin install vagrant-share
vagrant plugin install vagrant-disksize
vagrant init phoenixmedia/k3s
vagrant up 

#copy the kubeconfig file from the vm to be able to connect from outside

#install operator lifecycle manager
---

== Halyard Spinnaker
[source, shell]
----
# all hal commands https://spinnaker.io/docs/reference/halyard/commands/
# apply configuraiton change with
hal deploy apply


----

https://spinnaker.io/docs/setup/install/faq/


== Flagger

Prereq. setup FluxCD

brew install fluxcd/tap/flux
export GITHUB_TOKEN=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
export GITHUB_USER=caf3babe



== Tools comparison 

Problem description...
The comparison must take in a scientifical or pseudo-scientifical way as the problems described or not solveable using a mathematical approach. A deterministic approach is taken to rank the quality of the software solutions. The following categories are used to classify. 

* Meeting the expected requirements (1 to 5)
* Reliability level (MTBF—Mean Time Between Failure) (1…5)
* Quality level (“fitness to use” throughput, documentation, help function) (1….5)
* User-friendliness (1…5)
* Price
