Vagrant.configure("2") do |config|
  
  config.vm.define "halyard-spinnaker", primary: true do |instance|

    instance.vm.box = "bento/debian-10.13"
    instance.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    instance.vm.hostname = "halyard-spinnaker"

    instance.vm.provision "shell", inline: <<-SHELL
    # curl -sfL https://get.k3s.io | sh
    # cp /etc/rancher/k3s/k3s.yaml /vagrant/kubeconfig
    # sed -i "s/127.0.0.1/192.168.56.10/g" /vagrant/kubeconfig
    sudo useradd minio-user
    wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230106181118.0.0_amd64.deb -O minio.deb
    sudo dpkg -i minio.deb
    sudo mkdir -p /opt/minio && sudo chown -R minio-user:minio-user /opt/minio
    cat << EOF | sudo tee /etc/default/minio 
MINIO_VOLUMES="/opt/minio"
MINIO_OPTS="--console-address :9090 --address :9001"
EOF
    sudo systemctl start minio 
    curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh
    printf "Y\n" | sudo bash InstallHalyard.sh 
    SHELL

    instance.vm.network "private_network", ip: "192.168.56.10"
    instance.vm.network "forwarded_port", guest: 9000, host: 9000
    instance.vm.network "forwarded_port", guest: 9001, host: 9001
    instance.vm.network "forwarded_port", guest: 8084, host: 8084
  end
end

